### ISSUE TITLE
[1.5pt](Group-task): Set upLogin and RegistrationPage

### ISSUE THREAD

**Issue by Arturgouveia1970** [Arturgouveia1970/ror-recipe-app#4]
- [x] Login page and registration page:

-   should be built with Devise.
-   set up user controller.
-   set up user view.

**Comment by Arturgouveia1970** [comment]
[ ] Login page and registration page:
  - should be built with Devise.
  - set up user controller.
  - set up user-view.

**Comment by felixodette** [comment]
All done i believe. Have a look, check if i've left anything out.
